# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HtUAkr7qrTncbaktTSOOUI-1db-sLz2N
"""

from google.colab import files

uploaded = files.upload()

from PIL import Image
import matplotlib.pyplot as plt

content = Image.open("content.jpg")
style = Image.open("style.jpg")

style = style.resize(content.size)

blended = Image.blend(content, style, alpha=0.4)

plt.figure(figsize=(12,4))

plt.subplot(1,3,1)
plt.imshow(content)
plt.title("Content Image")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(style)
plt.title("Style Image")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(blended)
plt.title("Styled Output")
plt.axis("off")

plt.show()